In [ ]:
# Install necessary libraries
!pip install pandas sentence-transformers pycaret tensorflow scikit-learn

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 224.7/224.7 kB 4.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 486.1/486.1 kB 8.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 302.2/302.2 kB 9.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 42.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 165.0/165.0 kB 16.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 258.3/258.3 kB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.1/194.1 kB 20.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.9/79.9 MB 10.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 106.8/106.8 kB 12.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 80.7/80.7 kB 9.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.8/21.8 MB 

In [ ]:
# install full version
!pip install pycaret[full]

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 535.7/535.7 kB 6.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.7/85.7 kB 8.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 359.5/359.5 kB 9.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 287.8/287.8 kB 12.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 177.5/177.5 kB 8.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100.0/100.0 kB 11.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 380.1/380.1 kB 12.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.4/93.4 kB 10.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 107.7/107.7 kB 12.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.0/25.0 MB 42.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 72.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.3/139.3 kB 16.0 MB/s eta 0:00:00
     ━━━━━━━━━━━

In [ ]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import accuracy_score, recall_score, f1_score, mean_absolute_error, mean_squared_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from pycaret.clustering import *
from sentence_transformers import SentenceTransformer
from sklearn.metrics import silhouette_score, davies_bouldin_score
from sklearn.preprocessing import MinMaxScaler

In [ ]:
import codecs

# Buka file dengan codecs
with codecs.open('tourism_with_id.csv', 'r', encoding='utf-8', errors='ignore') as file:
    tourist = pd.read_csv(file)

# Tampilkan data
tourist.head()

Place_Id     Tempat Wisata                     Alamat  Rating  \
0         1    Masjidil Haram       Makkah Al Mukarramah     5.0   
1         2       Jabal Thaur              Jabal Al Nour     4.8   
2         3        Bukit Uhud  Uhud Mountain View Resort     4.7   
3         4       Masjid Quba                Quba Mosque     4.9   
4         5  Masjid Qiblatain           Qiblatain Mosque     4.8   

   Jarak dari Kakbah Mekkah (km)  
0                            0.0  
1                            3.5  
2                            5.0  
3                            6.2  
4                            7.1

In [ ]:
tourist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1212 entries, 0 to 1211
Data columns (total 5 columns):
 #   Column                         Non-Null Count  Dtype  
---  ------                         --------------  -----  
 0   Place_Id                       1212 non-null   int64  
 1   Tempat Wisata                  1212 non-null   object 
 2   Alamat                         1212 non-null   object 
 3   Rating                         1212 non-null   float64
 4   Jarak dari Kakbah Mekkah (km)  1212 non-null   float64
dtypes: float64(2), int64(1), object(2)
memory usage: 47.5+ KB


In [ ]:
tourist.describe()

Place_Id       Rating  Jarak dari Kakbah Mekkah (km)
count  1212.000000  1212.000000                    1212.000000
mean    606.500000     4.652063                    1326.831931
std     350.018571     0.092336                     512.116237
min       1.000000     4.000000                       0.000000
25%     303.750000     4.600000                    1242.000000
50%     606.500000     4.600000                    1295.000000
75%     909.250000     4.700000                    1594.000000
max    1212.000000     5.000000                    2540.000000

In [ ]:
# Load Data
rating = pd.read_csv('tourism_rating.csv')

NameError: name 'get_data' is not defined

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   User_Id        10000 non-null  int64
 1   Place_Id       10000 non-null  int64
 2   Place_Ratings  10000 non-null  int64
dtypes: int64(3)
memory usage: 234.5 KB


In [ ]:
rating.describe()

User_Id      Place_Id  Place_Ratings
count  10000.000000  10000.000000   10000.000000
mean     151.292700    219.416400       3.066500
std       86.137374    126.228335       1.379952
min        1.000000      1.000000       1.000000
25%       77.000000    108.750000       2.000000
50%      151.000000    220.000000       3.000000
75%      226.000000    329.000000       4.000000
max      300.000000    437.000000       5.000000

In [ ]:
print(f'Jumlah data tempat yang duplikat : {tourist.duplicated().sum()}')
print(f'Jumlah data rating yang duplikat : {rating.duplicated().sum()}')

Jumlah data tempat yang duplikat : 0
Jumlah data rating yang duplikat : 79


In [ ]:
rating.drop_duplicates(inplace=True)

In [ ]:
rating.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9921 entries, 0 to 9999
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   User_Id        9921 non-null   int64
 1   Place_Id       9921 non-null   int64
 2   Place_Ratings  9921 non-null   int64
dtypes: int64(3)
memory usage: 310.0 KB


In [ ]:
# Merge datasets on place_id/Place_Id
merged_data = pd.merge(rating, tourist, left_on='place_id', right_on='Place_Id')
print(merged_data.head())

   User_Id  Place_Id  Place_Ratings         Tempat Wisata  Alamat  Rating  \
0        1       179              3  St. Simeon Monastery   Aswan     4.7   
1       22       179              4  St. Simeon Monastery   Aswan     4.7   
2       40       179              3  St. Simeon Monastery   Aswan     4.7   
3       49       179              5  St. Simeon Monastery   Aswan     4.7   
4       74       179              3  St. Simeon Monastery   Aswan     4.7   

   Jarak dari Kakbah Mekkah (km)  
0                         1742.0  
1                         1742.0  
2                         1742.0  
3                         1742.0  
4                         1742.0  


In [ ]:
# Preprocessing
X = merged_df[['Tempat Wisata', 'Alamat', 'Place_Ratings']]

In [ ]:
# Identify columns with non-numeric data
non_numeric_cols = X.select_dtypes(include=['object']).columns

In [ ]:
# Standardize numeric columns
numeric_cols = X.select_dtypes(exclude=['object']).columns
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X[numeric_cols])

In [ ]:
# Compute cosine similarity matrix
cosine_sim = cosine_similarity(X_scaled)

In [ ]:
# Hugging Face Sentence Transformer
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-mpnet-base-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
X['input_text'] = X['Tempat Wisata'] + ' ' + X['Alamat']


In [ ]:
X_emb = model.encode(X['input_text'])


In [ ]:
# Calculate the cosine similarity matrix
cosine_sim = cosine_similarity(X_emb, X_emb)

In [ ]:
# Print the cosine similarity matrix
print(cosine_sim)

[[1.         1.         1.         ... 0.54768765 0.54768765 0.54768765]
 [1.         1.0000001  1.0000001  ... 0.54768765 0.54768765 0.54768765]
 [1.         1.0000001  1.0000001  ... 0.54768765 0.54768765 0.54768765]
 ...
 [0.54768765 0.54768765 0.54768765 ... 1.0000001  1.0000001  1.0000001 ]
 [0.54768765 0.54768765 0.54768765 ... 1.0000001  1.0000001  1.0000001 ]
 [0.54768765 0.54768765 0.54768765 ... 1.0000001  1.0000001  1.0000001 ]]


In [ ]:
# Clustering with PyCaret
from sklearn.cluster import KMeans
from sklearn.model_selection import GridSearchCV
exp_cluster = setup(data=X_emb, session_id=123)

In [ ]:
cluster_model = create_model('kmeans')
clusters = predict_model(cluster_model, data=pd.DataFrame(X_emb))
X['cluster'] = clusters['Cluster']
print(X.head())


Processing:   0%|          | 0/3 [00:00<?, ?it/s]

KeyError: "None of [Index(['feature_1', 'feature_2', 'feature_3', 'feature_4', 'feature_5',\n       'feature_6', 'feature_7', 'feature_8', 'feature_9', 'feature_10',\n       ...\n       'feature_759', 'feature_760', 'feature_761', 'feature_762',\n       'feature_763', 'feature_764', 'feature_765', 'feature_766',\n       'feature_767', 'feature_768'],\n      dtype='object', length=768)] are in the [columns]"

In [ ]:
def tune_model(model):
    """
    Fungsi untuk melakukan tuning model clustering K-Means.

    Args:
        model (KMeans): Model K-Means yang akan di-tune.

    Returns:
        KMeans: Model K-Means yang sudah dioptimalkan.
    """
    # Tentukan parameter yang akan di-tune
    param_grid = {
        'n_clusters': [3, 4, 5, 6, 7, 8, 9, 10],
        'init': ['k-means++', 'random'],
        'n_init': [10, 20, 30],
        'max_iter': [100, 200, 300]
    }

    # Lakukan grid search untuk mencari model terbaik
    grid_search = GridSearchCV(model, param_grid, cv=5)
    grid_search.fit(X_scaled)

    # Dapatkan model terbaik
    best_model = grid_search.best_estimator_

    return best_model

In [ ]:
cluster_model = create_model('kmeans')
best_model = tune_model(cluster_model)
clusters = best_model.predict(X_emb)
X['cluster'] = clusters
print(X.head())


Processing:   0%|          | 0/3 [00:00<?, ?it/s]

ValueError: X has 768 features, but KMeans is expecting 1 features as input.

In [ ]:
# Drop rows with non-numeric data
X = X.dropna(subset=non_numeric_cols)

In [ ]:
# Group by 'tempat wisata' and calculate the mean rating
grouped_df = merged_df.groupby(['Tempat Wisata', 'Alamat']).agg({'Place_Ratings': 'mean'}).reset_index()


In [ ]:
grouped_df.columns = ['Nama', 'Alamat', 'Rating']


In [ ]:
# Load pre-trained sentence transformer model
model = SentenceTransformer('paraphrase-MiniLM-L6-v2')

In [ ]:
# Encode the text data using the sentence transformer
encoded_text = model.encode(grouped_df['Nama'] + ' ' + grouped_df['Alamat'], show_progress_bar=True)


Batches:   0%|          | 0/14 [00:00<?, ?it/s]

In [ ]:
xtrain = pd.DataFrame(encoded_text)
xtrain['Rating'] = grouped_df['Rating'].values


In [ ]:
clustering_setup = setup(data=xtrain, normalize=True, silent=True)


TypeError: setup() got an unexpected keyword argument 'silent'